


# =============================================
# SONG SERVICE
# =============================================
#song.service.url=${SONG_SERVICE_URL}

# =============================================
# API GATEWAY
# =============================================
api:
  gateway:
    rl: ${API_GATEWAY_URL}

# =============================================
# S3 STORAGE
# =============================================
s3:
  storage:
    rl: ${S3_STORAGE_URL}
    bucket: ${S3_BUCKET_NAME}
    credentials:
      user: ${S3_USER}
      password: ${S3_PASSWORD}

# =============================================
# SERVICE REGISTRY
# =============================================
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

