server:
  port: '8181'
  
spring:
  datasource:
    username: user
    url: jdbc:postgresql://localhost:5432/resources_db
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: validate
    show-sql: 'false'

song:
  service:
    url: http://localhost:8180

eureka:
  client:
    enabled: false

api:
  gateway:
    url: http://localhost:8180
