apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-resource-service-config-map
  namespace: {{.Release.Namespace}}
data:
  SERVER_PORT: "8180"
  API_GATEWAY_URL: {{ .Release.Name | upper | printf "http://${%s-SONG-SERVICE_SERVICE_HOST}" }}:{{ .Release.Name | upper | printf "${%s-SONG-SERVICE_SERVICE_PORT}" }}
  SERVICE_REGISTRY_URL: "http://service-registry:8083/eureka"
  RESOURCES_DB_URL: {{ .Release.Name | upper | printf "jdbc:postgresql://${%s-RESOURCE-DB_SERVICE_HOST}:5432/resources_db" }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Name}}-resource-service
spec:
  type:  ClusterIP
  selector:
    app: {{.Release.Name}}-resource-service-pod
  ports:
    - port: 8180

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Name}}-resource-service-deployment
  labels:
    app: {{.Release.Name}}-resource-service-app
spec:
  replicas: {{ .Values.replicas.resourceService }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-resource-service-pod
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-resource-service-pod
    spec:
      containers:
        - name: {{.Release.Name}}-resource-service-pod
          image: {{ .Values.images.resourceService }}
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-resource-service-config-map
          env:
            - name: RESOURCES_DB_USR
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-resource-secret
                  key: username
            - name: RESOURCES_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-resource-secret
                  key: password
          ports:
            - containerPort: 8180
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /alive
              port: 8180
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8180
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /started
              port: 8180
            initialDelaySeconds: 20
            periodSeconds: 10
              
