apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-song-service-config-map
  namespace: {{.Release.Namespace}}
data:
  SERVER_PORT: "8180"
  API_GATEWAY_URL: {{ .Release.Name | upper | printf "http://${%s-RESOURCE-SERVICE_SERVICE_HOST}" }}:{{ .Release.Name | upper | printf "${%s-RESOURCE-SERVICE_SERVICE_PORT}" }}
  SERVICE_REGISTRY_URL: "http://service-registry:8083/eureka"
  SONGS_DB_URL: {{ .Release.Name | upper | printf "jdbc:postgresql://${%s-SONG-DB_SERVICE_HOST}:5432/songs_db" }}
  
---

apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Name}}-song-service
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-song-service-pod
  ports:
    - port: 8180

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Name}}-song-service-deployment
  labels:
    app: {{.Release.Name}}-song-service-app
spec:
  replicas: {{ .Values.replicas.songService }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-song-service-pod
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-song-service-pod
    spec:
      containers:
        - name: {{.Release.Name}}-song-service-pod
          image: {{ .Values.images.songService }}
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-song-service-config-map
          env:
            - name: SONGS_DB_USR
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-song-secret
                  key: username
            - name: SONGS_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-song-secret
                  key: password
          ports:
            - containerPort: 8180
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: {{.Release.Name}}-www-persistent-storage
              mountPath: /home
          livenessProbe:
#            exec:
#              command:
#                - cat
#                - /home/health
            httpGet:
              path: /alive
              port: 8180
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8180
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /started
              port: 8180
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: {{.Release.Name}}-www-persistent-storage
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-song-claim-test
