apiVersion: v1
kind: Secret
metadata:
  namespace: k8s-program
  name: {{.Release.Name}}-song-secret
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-song-db-config-map
  namespace: k8s-program
data:
  POSTGRES_DB: "songs_db"
  PGDATA: "/var/lib/postgresql/data/pgdata"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-song-db-init-config-map
  namespace: k8s-program
data:
  schema.sql: "CREATE TABLE IF NOT EXISTS public.song (
	\"year\" int4 NOT NULL,
  id int8 NOT NULL,
  resource_id int8 NULL,
  album varchar(255) NULL,
  artist varchar(255) NULL,
  length varchar(255) NULL,
  \"name\" varchar(255) NULL,
  CONSTRAINT song_pkey PRIMARY KEY (id)
  );
  
  CREATE UNIQUE INDEX IF NOT EXISTS song_pkey ON public.song USING btree (id);
  
  -- public.song_seq definition
  
  -- DROP SEQUENCE public.song_seq;
  
  CREATE SEQUENCE IF NOT EXISTS public.song_seq
  INCREMENT BY 50
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
  NO CYCLE;
  
  ALTER TABLE public.song
  ADD genre VARCHAR(255);"

  
---

apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: {{.Release.Name}}-song-db
  labels:
    app: {{.Release.Name}}-song-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: web
  selector:
    app: {{.Release.Name}}-song-db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: {{.Release.Name}}-song-db
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}-song-db # has to match .spec.template.metadata.labels
  serviceName: "{{.Release.Name}}-song-db"
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-song-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{.Release.Name}}-song-db
          image: postgres:13.3-alpine
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-song-db-config-map
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-song-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-song-secret
                  key: password
          ports:
            - containerPort: 5432
              name: web
          volumeMounts:
            - name: {{.Release.Name}}-www-persistent-storage
              mountPath: /var/lib/postgresql/data/pgdata
            - name: {{.Release.Name}}-song-db-init
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true
      volumes:
        - name: {{.Release.Name}}-song-db-init
          configMap:
            name: {{.Release.Name}}-song-db-init-config-map
  volumeClaimTemplates:
    - metadata:
        name: {{.Release.Name}}-www-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 1Gi
